//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaInventario.WSNotificacionDiferenciaAzure.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SistemaInventario.WSNotificacionDiferenciaAzure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td width=189 valign=top style=&apos;width:141.55pt;border:solid #999999 1.0pt;
        ///  mso-border-themecolor:text1;mso-border-themetint:102;border-bottom:solid #666666 1.5pt;
        ///  mso-border-bottom-themecolor:text1;mso-border-bottom-themetint:153;
        ///  mso-border-alt:solid #999999 .5pt;mso-border-themecolor:text1;mso-border-themetint:
        ///  102;mso-border-bottom-alt:solid #666666 1.5pt;mso-border-bottom-themecolor:
        ///  text1;mso-border-bottom-themetint:153;padding:0cm 5.4pt 0cm 5.4pt&apos;&gt;
        ///  &lt;p class=MsoNormal style=&apos;margin-bo [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CABECERA_TABLA_TD {
            get {
                return ResourceManager.GetString("CABECERA_TABLA_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr style=&apos;mso-yfti-irow:-1;mso-yfti-firstrow:yes;mso-yfti-lastfirstrow:yes&apos;&gt;
        /// 
        ///	@CONTENIDO_CABECERA
        /// 
        /// &lt;/tr&gt;.
        /// </summary>
        internal static string CABECERA_TABLA_TR {
            get {
                return ResourceManager.GetString("CABECERA_TABLA_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;td width=189 valign=top style=&apos;width:141.55pt;border-top:none;border-left:
        ///  none;border-bottom:solid #999999 1.0pt;mso-border-bottom-themecolor:text1;
        ///  mso-border-bottom-themetint:102;border-right:solid #999999 1.0pt;mso-border-right-themecolor:
        ///  text1;mso-border-right-themetint:102;mso-border-top-alt:solid #999999 .5pt;
        ///  mso-border-top-themecolor:text1;mso-border-top-themetint:102;mso-border-left-alt:
        ///  solid #999999 .5pt;mso-border-left-themecolor:text1;mso-border-left-themetint:
        ///  102;mso-bord [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CUERPO_TABLA_TD {
            get {
                return ResourceManager.GetString("CUERPO_TABLA_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;tr style=&apos;mso-yfti-irow:0&apos;&gt;
        ///	@CONTENIDO_TR
        /// 
        ///  &lt;/tr&gt;.
        /// </summary>
        internal static string CUERPO_TABLA_TR {
            get {
                return ResourceManager.GetString("CUERPO_TABLA_TR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{font-family:&quot;Cambria Math&quot;;
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;
        ///	mso-font-charset:1;
        ///	mso-generic-font-family:roman;
        ///	mso-font-format:other;
        ///	mso-font-pitch:variable;
        ///	mso-font-signature:0 0 0 0 0 0;}
        ///@font-face
        ///	{font-family:Calibri;
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;
        ///	mso-font-charset:0;
        ///	mso-generic-font-family:swiss;
        ///	mso-font-pitch:variable;
        ///	mso-font-signature:-536858881 -1073732485 9 0 511 0;}
        /// /* Style Definitions */
        /// p.Ms [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PAGINA {
            get {
                return ResourceManager.GetString("PAGINA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;table class=MsoTable15Grid1Light border=1 cellspacing=0 cellpadding=0
        /// style=&apos;border-collapse:collapse;border:none;mso-border-alt:solid #999999 .5pt;
        /// mso-border-themecolor:text1;mso-border-themetint:102;mso-yfti-tbllook:1184;
        /// mso-padding-alt:0cm 5.4pt 0cm 5.4pt&apos;&gt;
        ///
        ///	@CONTENIDO_TABLA
        ///
        ///
        ///&lt;/table&gt;.
        /// </summary>
        internal static string TABLA {
            get {
                return ResourceManager.GetString("TABLA", resourceCulture);
            }
        }
    }
}
