using System;
using System.Data;
using System.Data.SqlClient;
using System.Collections.Generic;

public class DocumentoVentaCabCE
{
    public int Ranking { get; set; }
    public int Codigo { get; set; }
    public int CodDocumentoVenta { get; set; }
    public int CodDetDocumentoVenta { get; set; }
    public int CodAlmacen { get; set; }
    public int CodTipoDoc { get; set; }
    public int CodSerializacionCab { get; set; }
    public int CodProducto { get; set; }
    public int FlagAcuenta { get; set; }
    public string SerieDoc { get; set; }
    public string NumeroDoc { get; set; }
    public string Serie { get; set; }
    public int CodTipoOperacionNC { get; set; }
    public int CodFactura_Asociada { get; set; }
    public int CodVendedor { get; set; }
    public int CodCajaFisica { get; set; }
    public int CodCajaChica { get; set; }
    public DateTime FechaEmision { get; set; }
    public int CodCliente { get; set; }
    public int CodEstado { get; set; }
    public int CodFormaPago { get; set; }
    public DateTime FechaVencimiento { get; set; }
    public DateTime FechaCancelacion { get; set; }
    public int CodMoneda { get; set; }
    public decimal TipoCambio { get; set; }
    public decimal CobranzaDolares { get; set; }
    public decimal DeudaDolares { get; set; }
    public decimal CobroOperacionSoles { get; set; }
    public decimal CobroOperacionDolares { get; set; }
    public decimal Comision { get; set; }
    public decimal GastosOperativos { get; set; }
    public string Enviado { get; set; }
    public string Observacion { get; set; }
    public int CodUsuario { get; set; }
    public int CodUsuarioAnulacion { get; set; }
    public int Asiento { get; set; }
    public string CuentaContable { get; set; }
    public int Flag { get; set; }
    public string ObservacionesCliente { get; set; }
    public decimal Detracciones { get; set; }
    public int CodGuia { get; set; }
    public int CodUsuarioAprobacion { get; set; }
    public decimal Descuento { get; set; }
    public int CodProforma { get; set; }
    public int CodEmpresa { get; set; }
    public decimal Saldo { get; set; }
    public string XmlDetalle { get; set; }
    public string MsgError { get; set; }
    public string Marca { get; set; }
    public int FlagGuia { get; set; }
    public string Destino { get; set; }
    public string SerieGuia { get; set; }
    public string NumeroGuia { get; set; }
    public int NotaPedido { get; set; }
    public DateTime FechaTraslado { get; set; }
    public string DscTasa { get; set; }
    public int IdFamilia { get; set; }
    public decimal TasaIgv { get; set; }
    public decimal DeudaSoles { get; set; }
    public int CodDetalle { get; set; }
    public int CodClasificacion { get; set; }
    public DateTime Desde { get; set; }
    public DateTime Hasta { get; set; }
    public int CodTasa { get; set; }
    public int CodBanco { get; set; }
    public int CodigoTemporal { get; set; }
    public int CodigoTemporalPago { get; set; }
    public int CodMedioPago { get; set; }
    public string NroOperacion { get; set; }
    public DateTime FechaOperacion { get; set; }
    public DateTime Recepcion { get; set; }
    public string Responsable { get; set; }
    public string SerieOC { get; set; }
    public string NumeroOC { get; set; }
    public string Cliente { get; set; }
    public string Vendedor { get; set; }
    public int CodCtaBancaria { get; set; }
    public decimal CobranzaSoles { get; set; }
    public int CodCobranza { get; set; }
    public decimal Cantidad { get; set; }
    public int CodTipoOperacion { get; set; }
    public int CodSerie { get; set; }
    public string NroRuc { get; set; }
    public string RazonSocial { get; set; }
    public string ApePaterno { get; set; }
    public string ApeMaterno { get; set; }
    public string NroDni { get; set; }
    public string Nombres { get; set; }
    public int CodTipoCliente { get; set; }
    public int CodClaseCliente { get; set; }
    public int CodDepartamento { get; set; }
    public int CodProvincia { get; set; }
    public int CodDistrito { get; set; }
    public int Periodo { get; set; }
    public string Direccion { get; set; }
    public int CodProductoCorrecto { get; set; }
    public int CodProductoIncorrecto { get; set; }
    public int CodComprobanteCaja { get; set; }
    public decimal SubTotal { get; set; }
    public decimal Igv { get; set; }
    public decimal Total { get; set; }
    public decimal Acuenta { get; set; }
    public decimal AcuentaNV { get; set; }
    public string CodAlterno { get; set; }
    public int CodFacturaAnterior { get; set; }
    public int CodAlmacenDestino { get; set; }
    public int FlagCSIgv { get; set; }
    public int CodDireccion { get; set; }
    public string IP { get; set; }
    public int DesdeInt { get; set; }
    public int HastaInt { get; set; }
    public int FlagFormulario { get; set; }
    public int CodAlmacenFisicoDesde { get; set; }
    public int CodAlmacenFisicoHasta { get; set; }
    public string Tipo { get; set; }
    public decimal Tasa { get; set; }
    public int CodigoPagina { get; set; }
    public int CodTraslado { get; set; }
    public string Descripcion { get; set; }
    public long IDPruebasExcelCab { get; set; }
    public int FlagIgv { get; set; }
    public string Placa { get; set; }
    public string Placa2 { get; set; }
    public string Placa3 { get; set; }
    public string Placa4 { get; set; }
    public string KM { get; set; }
    public string PlacaTraslado { get; set; }
    public string Partida { get; set; }
    public string DireccionCompleta { get; set; }
    public int FlagRetencion { get; set; }
    public int FlagLetra { get; set; }
    public int NotaVenta { get; set; }
    public string Transportista { get; set; }
    public string Licencia { get; set; }
    public string NuBultos { get; set; }
    public int CodTransportista { get; set; }
    public int CodDireccionTransportista { get; set; }
    public string DireccionTransportista { get; set; }
    public string Peso { get; set; }
    public string Correo { get; set; }
    public string NroOC { get; set; }
    public string DireccionTraslado { get; set; }
    public int FlagRenovar { get; set; }
    public string ArchivoCDR { get; set; }
    public int CodEmpleado { get; set; }
    public int FlagNotaVentaANTIGUA { get; set; }
    public int FlagFacturaANTIGUA { get; set; }
    public int FlagComisionable { get; set; }
    public decimal Vuelto2 { get; set; }
    public int TipoDevolucion { get; set; }
    public int CodMonedaVuelto { get; set; }
    public decimal Vuelto { get; set; }
    public string xmlLineas { get; set; }
    public string xmlFamilias { get; set; }
    public string xmlMarcas { get; set; }
    public int CodMotivo { get; set; }
    public DateTime FechaDua { get; set; }
    public int TipoReporte { get; set; }
    public int SolicitarDescuento { get; set; }
    public string Conexion { get; set; }
    public string Usuario { get; set; }
    public string ObservacionAnulacion { get; set; }
    public DateTime FechaSaldo { get; set; }
    public int CodProductoSuperior { get; set; }
    public int CodArticulo { get; set; }
    public int CodUndMedida { get; set; }
    public decimal Precio { get; set; }
    public int CodProyecto { get; set; }
    public int NroSemana { get; set; }
    public int CodSemana { get; set; }
    public int CodRegimenLaboral { get; set; }
    public string NroRucTransportista { get; set; }
    public string DepartamentoTransportista { get; set; }
    public string ProvinciaTransportista { get; set; }
    public string DistritoTransportista { get; set; }
    public int FlagOC { get; set; }
    public int CodDepartamentoTransportista { get; set; }
    public int CodProvinciaTransportista { get; set; }
    public int CodDistritoTransportista { get; set; }
    public int CodConductor { get; set; }
    public int FlagKM { get; set; }
    public string DniConductor { get; set; }
    public string NombreConductor { get; set; }
    public int CodTipoFormato { get; set; }
    public int CodOrdenPedido { get; set; }
    public int FlagPlaca { get; set; }
    public int FlagPreImport { get; set; }
    public DateTime FechaLlegada { get; set; }
    public int CodSemanaInicio { get; set; }
    public int CodSemanaFinal { get; set; }
    public int CodPeriodo { get; set; }
    public string Anexo { get; set; }
    public int Numero { get; set; }
    public int FlagTodo { get; set; }
    public int Motorizado { get; set; }
    public int CantidadABC { get; set; }
    public int Cantidad173 { get; set; }
    public int Cantidad250 { get; set; }
    public int Codliquidacion { get; set; }
    public int IDFamilia { get; set; }
    public string UsuarioPermiso { get; set; }
    public string ClavePermiso { get; set; }
    public string ObservacionPermiso { get; set; }
    public int Cobrador { get; set; }
    public string Celular { get; set; }
    public string NroRecibo { get; set; }
    public string NombreAgencia { get; set; }
    public DateTime DesdeCancelacion { get; set; }
    public string GuiaAgencia { get; set; }
    public DateTime HastaCancelacion { get; set; }
    public string ClaveAgencia { get; set; }
    public int Ruta { get; set; }
    public int chkFecha { get; set; }
    public int chkRegistro { get; set; }
    public int FlagConCodigo { get; set; }
    public int chkMarca { get; set; }

    public int codMarca { get; set; }

    public int chkCliente { get; set; }

    public int Peso_KG { get; set; }

    public int CodDoc { get; set; }

    public string Codigos { get; set; }

    public int coddoc { get; set; }

    public int Codigodetalle { get; set; }
    public decimal ComisionTarjeta { get; set; }
    public int CodTipoPlan { get; set; }
    public decimal Kilometros { get; set; }
    public int CodVehiculo { get; set; }

}



public class FiltroCobranzas : DocumentoVentaCabCE {

    public int FlagFiltroFecha { get; set; }
    public DateTime FechaDesde { get; set; }
    public DateTime FechaHasta { get; set; }
    public int FlagFiltroMonto { get; set; }
    public decimal MontoDesde { get; set; }
    public decimal MontoHasta { get; set; }
}
